[[redirects]]
from = "https://www.kinganointing-blog.netlify.app"
to = "https://kinganointing-blog.netlify.app"
status = 301
force = true

[[redirects]]
from = "https://www.kinganointing-blog.netlify.app"
to = "https://kinganointing-blog.netlify.app"
status = 301
force = true
