// module.exports = {
// By default, Docusaurus generates a sidebar from the docs folder structure
// tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
module.exports = {
  mySidebar: [
    {
      type: "autogenerated",
      dirName: ".", // generate sidebar from the docs folder (or versioned_docs/<version>)
    },
  ],
};
