// module.exports = {
// By default, Docusaurus generates a sidebar from the docs folder structure
// tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
module.exports = {
  docs: [
    {
      type: "doc",
      id: "intro",
    },
    {
      type: "category",
      label: "Solutions to Bugs from Day to Day Activities",
      items: ["hello-world"],
    },
  ],
};
